### ISSUE TITLE
请问如何构建自己的ROM呢

### ISSUE THREAD

**Issue by Jackjun724** [dqzg12300/MikRom#1]
有相关的教程吗？

**Comment by dqzg12300** [comment]
> 有相关的教程吗？

你可以先自己尝试编译aosp成功。网上教程非常多。在ubuntu下很好编译

**Comment by Jackjun724** [comment]
> > 有相关的教程吗？
> 
> 你可以先自己尝试编译aosp成功。网上教程非常多。在ubuntu下很好编译

给出的镜像要怎么安装 :)

**Comment by dqzg12300** [comment]
> 有相关的教程吗？

twrp刷进去即可
