### ISSUE TITLE
AOsp10r2

### ISSUE THREAD

**Issue by yxbbing123** [dqzg12300/MikRom#11]
下载最新代码编译报错。
device/ti/beagle_x15/AndroidProducts.mk:20: error: build/target/product/AndroidProducts.mk: No such file or directory
14:31:45 dumpvars failed with: exit status 1

**Comment by dqzg12300** [comment]
看错误应该和我的代码无关。过几天我会放出一份完整的全量包。直接解压就可以编译的。

**Comment by yxbbing123** [comment]
Aosp10r2  编译是不是漏了文件没有上传？ 原来FartExt覆盖可以编译，

**Comment by dqzg12300** [comment]
应该是漏了啥文件。你看下readme中的下载地址，我已经更新放出了完整源码下载地址。
