### ISSUE TITLE
大佬，期待一个taimen的镜像

### ISSUE THREAD

**Issue by CoderYanKang** [dqzg12300/MikRom#14]
我编了几次都没有成功

**Comment by dqzg12300** [comment]
等段时间吧。近期因为疫情被封印了。没有设备。等我回去了给你编译一份。或者你也可以把编译的问题放上来。

**Comment by CoderYanKang** [comment]
感谢回复，之前用的官方的aosp进行代码替换出错，下载了你的完整文件，编译成功了，检测服务也有了

**Comment by huaerxiela** [comment]
> 感谢回复，之前用的官方的aosp进行代码替换出错，下载了你的完整文件，编译成功了，检测服务也有了

请教下，你是下载了作者提供的百度网盘的aosp10r2源码，然后再拉git上作者修改的aosp10r2文件，覆盖之后，再编译，然后成功的吗？擦嘞，周末我这样搞了下失败了。。。

**Comment by CoderYanKang** [comment]
> 

下载作者百度网盘的aosp10r2完整源码，然后我要编译taimen的，在google官网下载响应手机r2的驱动文件进行替换，再编译的https://developers.google.com/android/drivers#taimen，你需要找你自己的设备。

**Comment by huaerxiela** [comment]
> > 
> 
> 下载作者百度网盘的aosp10r2完整源码，然后我要编译taimen的，在google官网下载响应手机r2的驱动文件进行替换，再编译的https://developers.google.com/android/drivers#taimen 你需要找你自己的设备驱动进行替换。

懂了，也就是说，你还没有进行这一步
“再拉git上作者修改的aosp10r2文件，覆盖之后”
直接就替换vendor就编译了
谢谢哥，回去我再试试

**Comment by CoderYanKang** [comment]
> 懂了，也就是说，你还没有进行这一步 “再拉git上作者修改的aosp10r2文件，覆盖之后” 直接就替换vendor就编译了 谢谢哥，回去我再试试

不客气，直接替换vendor，编译就可以了
