### ISSUE TITLE
Aosp10r2_blueline_1.0.1线刷包报错

### ISSUE THREAD

**Issue by freeloop4032** [dqzg12300/MikRom#16]
1. 直接修改线刷包为image-blueline-qp1a.190711.020.zip替换官方后，报错提示：
Device product is 'blueline'.
Update requires 'marlin' or 'sailfish'.

fastboot: error: requirements not met!
Press any key to exit...
2.用官方rom里面的android-info.txt替换后，报错提示：
fastboot: error: could not load 'product.img': No such file or directory

佬，所以说，这个blueline应该怎么刷机，求助

**Comment by dqzg12300** [comment]
由于我没有这个设备测试，所以这个编译有点问题暂时排查不了，你可以选择下载官方的包后，将我这个版本的system.img替换进去后刷机。这样也可以使用。只是缺少了内核几个地方的修改。不过也可以正常使用

**Comment by freeloop4032** [comment]
> 由于我没有这个设备测试，所以这个编译有点问题暂时排查不了，你可以选择下载官方的包后，将我这个版本的system.img替换进去后刷机。这样也可以使用。只是缺少了内核几个地方的修改。不过也可以正常使用

貌似也不行，刷机过程没有问题，但是刷完一直卡bootloader，提示：no valid slot to boot

**Comment by dqzg12300** [comment]
应该不会吧。你直接刷官方的包能正常进去吗？

**Comment by dqzg12300** [comment]
我重新编译一个。晚点放上去你试试。

**Comment by freeloop4032** [comment]
> 已经更新下载地址，你重新下载试试看
1.最新这个包可以了，但是刷的时候，直接flash-all.bat失败，不能自己跳到fastbootd。手动进入fastbootd，然后直接在最新编译的包解压目录下，挂一下 ANDROID_PRODUCT_OUT的环境变量，然后fastboot flashall -w ，完美刷入！
2.大佬牛逼！
