### ISSUE TITLE
脱壳失败，提示：detect_tracer() have detected tracer, pid: 808

### ISSUE THREAD

**Issue by ohyeah521** [dqzg12300/MikRom#17]
脱壳失败，提示：detect_tracer() have detected tracer, pid: 808

样本下载地址：链接: https://pan.baidu.com/s/10lnVgNRvKKf7PZdBCPt7tw?pwd=upfa 提取码: upfa 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by dqzg12300** [comment]
我测试能正常脱呀
<img width="789" alt="image" src="https://user-images.githubusercontent.com/19391415/167751847-ed25ef77-f2cc-4425-b73f-121adea8766b.png">

**Comment by ohyeah521** [comment]
奇怪了，我这里提示这个错误，Pixel4 XL，Android10 ，userdebug模式
![微信截图_20220511143033](https://user-images.githubusercontent.com/1449374/167783344-c25489e1-83fa-40c6-a5a3-64c01e339165.png)

**Comment by dqzg12300** [comment]
日志里面搜索mikrom能找到相关日志吗？我测试的也是userdebug版本。能正常脱的。可能你没刷好。adb shell 然后service list|grep mikrom   看看能找到我的服务不

**Comment by ohyeah521** [comment]
> g版本。能

我用的是fartext版本，没有用mikrom，它们的脱壳代码是一样的吧

**Comment by dqzg12300** [comment]
脱壳功能差不多。区别不大。你可以刷mikrom的试一下看看

**Comment by ohyeah521** [comment]
测试机是pixel4 XL，mikrom这个代码不支持这个设备
