### ISSUE TITLE
请教一个问题，ART_USE_CXX_INTERPRETER没有使用

### ISSUE THREAD

**Issue by ohyeah521** [dqzg12300/MikRom#18]
我在mikrom的art/runtime/Android.bp 中发现没有使用ART_USE_CXX_INTERPRETER这个宏，也没有修改下面的地方
//interpreter.cc
static constexpr InterpreterImplKind kInterpreterImplKind = kSwitchImplKind;

请问这最终是怎么走的？mikrom的代码是没有强制走switch型解释器吗？

**Comment by dqzg12300** [comment]
因为全部强制走解释器会导致性能较慢，所以我在其他地方添加逻辑控制是否走解释器执行。

**Comment by ohyeah521** [comment]
谢谢解答，使用这个宏ART_USE_CXX_INTERPRETER还会导致setting（设置）这个apk随机崩溃。我在看看代码，怎么改的
