### ISSUE TITLE
能不能嫖个pixel sailfish

### ISSUE THREAD

**Issue by lr-zhao** [dqzg12300/MikRom#2]

**Comment by dqzg12300** [comment]
> 

这几天有空编译一个放上来

**Comment by lr-zhao** [comment]
> > 
> 
> 这几天有空编译一个放上来
好的 ，期待一手

**Comment by xwopen** [comment]
期待 sailfish  的镜像

**Comment by zixing131** [comment]
同想要个sailfish镜像

**Comment by dqzg12300** [comment]
sailfish的驱动没找到。编译的进不去。我准备迁移到aosp一份。到时候aosp的版本再放个sailfish的镜像。

**Comment by lr-zhao** [comment]
我当时也下了一份那个源码，编译也是进不去，只有两个选项


理想三旬
***@***.***

Android


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dqzg12300/MikRom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dqzg12300/MikRom] 能不能嫖个pixel sailfish (Issue #2)





 
sailfish的驱动没找到。编译的进不去。我准备迁移到aosp一份。到时候aosp的版本再放个sailfish的镜像。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dqzg12300** [comment]
aosp10 sailfish已更新。
