### ISSUE TITLE
Aosp10r2_blueline_1.0.1线刷包 需要下那个官方的rom去替换文件

### ISSUE THREAD

**Issue by HuRuWo** [dqzg12300/MikRom#20]
我下载了最后一个Android10版本对不上

**Comment by dqzg12300** [comment]
额。不会吧。我现在也是用的blueline的版本。一直在正常使用啊。明天我重新上传一份我在使用版本把

**Comment by dqzg12300** [comment]
哦。对了。我之前测试的时候，发现好像在win下刷会有问题进步了fastbootd。在ubuntu或者mac下刷就一切正常。建议你尝试一下看看

**Comment by king1982** [comment]
> 

是不是提示：
--------------------------------------------
Bootloader Version...: 8996-012001-1908071822
Baseband Version.....: 8996-130361-1905270421
Serial Number........: FA6AR0304504
--------------------------------------------
extracting android-info.txt (0 MB) to RAM...
Checking 'product'                                 OKAY [  0.005s]
Checking 'version-bootloader'                      FAILED

Device version-bootloader is '8996-012001-1908071822'.
Update requires '8996-012001-1907011432'.

fastboot: error: requirements not met!
Press any key to exit...

**Comment by cc-404** [comment]
> 替换之后报错 Partition should be flashed in fastbootd' 单独刷原生官方包是可以的

fastboot reboot-fastboot 命令可以进入fastbootd模式，进入fastbootd模式后就可以刷入

**Comment by dqzg12300** [comment]
aosp10r2_blueline_1.0.1线刷包 链接: https://pan.baidu.com/s/15pcX9HFHOIYLVZtnV9j13g 密码: dlsu
你确定一下是不是下载的这个包

**Comment by dqzg12300** [comment]
刷机视频已经更新在readme，去看看blueline在win的刷机教程。
