### ISSUE TITLE
我问大佬编一个aosp10 r17的mikRom包

### ISSUE THREAD

**Issue by bike3097a** [dqzg12300/MikRom#21]
如题，希望采纳。

**Comment by bike3097a** [comment]
> 如题，希望采纳。

**Comment by dqzg12300** [comment]
最近没有捣鼓了。以后考虑直接迁移到aosp12了

**Comment by bike3097a** [comment]
那我的机型不支持安卓12呀 那是不是后期只能自己编译安卓10了，你的脱壳方法，必须通过as来脱壳吗？

**Comment by bike3097a** [comment]
我测试了，没有用呀，里面没有dump文件夹

**Comment by dqzg12300** [comment]
目录是 /sdcard/Android/data/<PackageName>/files/dump。你看看是不是搞错了

**Comment by bike3097a** [comment]
没有错，
![IMG_20220622_155108](https://user-images.githubusercontent.com/72074704/174983243-bd6e4eae-002f-41a5-a6c4-5385876074e4.jpg)
![IMG_20220622_154836](https://user-images.githubusercontent.com/72074704/174983273-0b350083-68ee-4dac-b989-e28f9a95967d.jpg)
你看下是不是有问题。

**Comment by dqzg12300** [comment]
应该是mikmanager要更新下。我上传了下对应的v1.0.1 mikmanager，你试一下看看
