### ISSUE TITLE
爱加密的那个app，我用frida-dumpdex工具成功dump出来了

### ISSUE THREAD

**Issue by bike3097a** [dqzg12300/MikRom#24]
如题，而且没有闪退。

**Comment by dqzg12300** [comment]
那说明是整体壳呀。整体壳的情况不需要完整调用跑完。进去跑一下就直接脱出来了的。

**Comment by bike3097a** [comment]
嗯 我用 frida-dexdump工具脱完，打开里面好多nop，有空录制视频讲解nop如何还原回来呗，那个修复后的一样有nop，另外两个dex大小都一样是什么问题，我想通过手动修复应该用啥去修复呀？最后一个问题，下一个版本多久发布呀？

**Comment by dqzg12300** [comment]
nop说明没有脱好，只是把那层整体壳脱了，还有一个抽取壳。抽取壳的脱壳之前我有发视频讲。不过最近发现b站发的使用教程全军覆没了。回头我看看放哪里上传好点吧

**Comment by bike3097a** [comment]
谢谢呀老大
