### ISSUE TITLE
IDA调试慢的问题是否已经解决了？

### ISSUE THREAD

**Issue by viruscoding** [dqzg12300/MikRom#28]
反复看了art修改的代码也没有找到原因

**Comment by bike3097a** [comment]
请问怎么通过ida调试呀  不是有个叫android server 的文件启动 才可以调试吗？

**Comment by viruscoding** [comment]
@bike3097a 是的，android server调试，单步很慢

**Comment by dqzg12300** [comment]
调试慢的问题可能和我修改到指令相关的处理较多。那些判断可能就是影响到了某个东西执行的效率。下个版本我会重构。到时候会想办法处理掉这个问题。

**Comment by viruscoding** [comment]
> > @bike3097a 是的，android server调试，单步很慢
> 
> 有个问题，mikROM不支持root，你是怎么调试的呀？

![image](https://user-images.githubusercontent.com/12998222/175949529-17b0c3e7-b1af-4a1a-8db9-204950cd7c92.png)

mikrom编译类型userdebug，怎么会没有root呢？
```
adb push android_server /
su
chmod 777 android_server
android_server
```
看雪有很多调试文章。

**Comment by viruscoding** [comment]
> 调试慢的问题可能和我修改到指令相关的处理较多。那些判断可能就是影响到了某个东西执行的效率。下个版本我会重构。到时候会想办法处理掉这个问题。

好的，谢谢大佬，期待新版本

**Comment by bike3097a** [comment]
> > > @bike3097a 是的，android server调试，单步很慢
> > 
> > 
> > 有个问题，mikROM不支持root，你是怎么调试的呀？
> 
> ![image](https://user-images.githubusercontent.com/12998222/175949529-17b0c3e7-b1af-4a1a-8db9-204950cd7c92.png)
> 
> mikrom编译类型userdebug，怎么会没有root呢？
> 
> ```
> adb push android_server /
> su
> chmod 777 android_server
> android_server
> ```
> 
> 看雪有很多调试文章。

请问你这个是在哪里找到的呀？
