### ISSUE TITLE
是否可以弄个piexl2的补丁包，或者固件？

### ISSUE THREAD

**Issue by zbx911** [dqzg12300/MikRom#3]
同上

**Comment by dqzg12300** [comment]
你可以看看具体要安装哪个适配驱动包。我可以重新编译一份给你。不过我记得我选择编译的版本应该可以兼容pixel2才对。我没有这个设备，你可以验证试一下。下面是我编译的版本。来源连接https://source.android.com/setup/start/build-numbers?hl=zh-cn

QP1A.190711.020 | android-10.0.0_r2 | Android10 | Pixel 3a XL、Pixel 3a、Pixel 3 XL、Pixel 3、Pixel 2 XL、Pixel 2、Pixel XL、Pixel | 2019-09-05

**Comment by zbx911** [comment]
我的是 QP3A.190705.001，也可以加我q，交流892908930

**Comment by zbx911** [comment]
> 你可以看看具体要安装哪个适配驱动包。我可以重新编译一份给你。不过我记得我选择编译的版本应该可以兼容pixel2才对。我没有这个设备，你可以验证试一下。下面是我编译的版本。来源连接https://source.android.com/setup/start/build-numbers?hl=zh-cn
> 
> QP1A.190711.020 | android-10.0.0_r2 | Android10 | Pixel 3a XL、Pixel 3a、Pixel 3 XL、Pixel 3、Pixel 2 XL、Pixel 2、Pixel XL、Pixel | 2019-09-05

想要你的mikrom 不是内核驱动包

**Comment by ohyeah521** [comment]
求此版本，

QQ3A.200805.001 | android-10.0.0_r41 | Android10 | Pixel 2、Pixel 2 XL、Pixel 3、Pixel 3a、Pixel 3a XL、Pixel 3 XL、Pixel 4、Pixel 4 XL | 2020-08-05
-- | -- | -- | -- | --



</body>
</html>

**Comment by General110** [comment]
> 求Pixel 4 XL的此版本，
> 
> QQ3A.200805.001	android-10.0.0_r41	Android10	Pixel 2、Pixel 2 XL、Pixel 3、Pixel 3a、Pixel 3a XL、Pixel 3 XL、Pixel 4、Pixel 4 XL	2020-08-05

同求Pixel 3 的此版本

我编译了好几回都编译失败 太难了...........

You have tried to change the API from what has been previously released in
an SDK.  Please fix the errors listed above.

error: Removed method android.app.admin.DevicePolicyManager.setAlwaysOnVpnPackage(android.content.ComponentName,String,boolean) [RemovedMethod]

**Comment by dqzg12300** [comment]
在readme的下载地址中，aosp的完整源码已放出。需要编译啥版本可以自行捣鼓了。
