### ISSUE TITLE
aosp10r2_blueline_1.0.1 面具安装报错

### ISSUE THREAD

**Issue by AlifeLine** [dqzg12300/MikRom#32]
aosp10r2_blueline_1.0.1 面具安装报错
提升不支持安装到外置存储卡

**Comment by dqzg12300** [comment]
最后一次修改有修复这个。不过修复后的我只编译了marlin的

**Comment by AlifeLine** [comment]
😂，能帮忙编译下blueline吗

**Comment by AlifeLine** [comment]
自己编译了一版，这个版本正常的
链接：https://pan.baidu.com/s/1wGr5zAvKsyMGTWWO0XIWUA?pwd=x1wf 
提取码：x1wf
