### ISSUE TITLE
刷机问题

### ISSUE THREAD

**Issue by Avenue-le** [dqzg12300/MikRom#33]
我需要先编译，然后再刷机吗？？，下载官方镜像之后，下载对应的文件，替换image压缩包，刷机报错呢
![image](https://user-images.githubusercontent.com/34837749/180646034-b5100f4c-e583-440a-abae-a1fa68b406d4.png)

**Comment by dqzg12300** [comment]
使用fastboot flashall -w的方式刷机

**Comment by Avenue-le** [comment]
> 
我的kali是否需要配置安卓源码编译环境？？ 我是没有弄环境，直接下载压缩包和镜像，直接刷机的，失败了

**Comment by dqzg12300** [comment]
不需要的。其他小伙伴也碰到过这个问题。其他人的解决办法你试试看。fastboot reboot-fastboot 命令可以进入fastbootd模式，进入fastbootd模式后就可以刷入。

**Comment by Avenue-le** [comment]
> 不需要的。其他小伙伴也碰到过这个问题。其他人的解决办法你试试看。fastboot reboot-fastboot 命令可以进入fastbootd模式，进入fastbootd模式后就可以刷入。

我是直接下载项目的压缩包，压缩包改名覆盖里面的image的压缩包， 把之前image雅座宝删除了，但是刷机失败
截图如下：
![image](https://user-images.githubusercontent.com/34837749/182027526-7c48b6c0-717e-4c9a-ba69-519afbbc93f5.png)
![image](https://user-images.githubusercontent.com/34837749/182027545-e2f053eb-ea23-4e58-bf5e-282e00cd4f3f.png)

请大佬帮我看看

**Comment by dqzg12300** [comment]
先设置环境变量ANDROID_PRODUCT_OUT为img目录。然后再刷

**Comment by Avenue-le** [comment]
> 
大佬，可以加个微信吗？？

**Comment by Avenue-le** [comment]
> 我刷成功了，但是安装manager.apk ， 打开闪退

**Comment by apsonLi** [comment]
我也刷成功了，但是 serviec 列表没有 mikrom service

**Comment by apsonLi** [comment]
这导致了 manager.apk 的闪退

**Comment by apsonLi** [comment]
版本 是 blueline

**Comment by Avenue-le** [comment]
> 我的版本和你的一样啊， 不知道为什么

**Comment by apsonLi** [comment]
fastboot flashall -w
重新刷了之后 可以了

**Comment by Avenue-le** [comment]
> fastboot flashall -w 重新刷了之后 可以了

我试过好几次了

**Comment by dqzg12300** [comment]
过段时间我出个刷机视频的教程吧。

**Comment by Avenue-le** [comment]
我刷了，还是没成功

**Comment by dqzg12300** [comment]
先刷官方的包。然后再我这个刷一次试试看

**Comment by Avenue-le** [comment]
官方包没问题啊，今天刷成功，但是rom没成功，
![image](https://user-images.githubusercontent.com/34837749/192552082-8ac07b32-e146-4080-91eb-6d9ddef12d08.png)
这是w我的image 文件内容

**Comment by dqzg12300** [comment]
blueline win下推荐使用fastboot flashall -w刷机。我这边日常用机也是blueline的。

**Comment by Avenue-le** [comment]
> 

> blueline win下推荐使用fastboot flashall -w刷机。我这边日常用机也是blueline的。
![Uploading image.png…]()
我是在kali 上用 fastboot flashall -w 刷机的

**Comment by Avenue-le** [comment]
> blueline win下推荐使用fastboot flashall -w刷机。我这边日常用机也是blueline的。
我刷成功了，但是手机没有root ，安装 managenr 直接闪退， 这是rom刷好了？？

**Comment by Avenue-le** [comment]
> 

是不是没有刷成功
![image](https://user-images.githubusercontent.com/34837749/192678072-ed40dfc7-3b62-499b-8c26-11e2aefe63ea.png)

我也是 blueine去
![image](https://user
![image](https://user-images.githubusercontent.com/34837749/192678116-9c933c3d-1c71-4a02-9a0b-6fb1321f11e2.png)

**Comment by dqzg12300** [comment]
你下载的哪个包？晚上我测试一下看看

**Comment by Avenue-le** [comment]
> 你下载的哪个包？晚上我测试一下看看

https://dl.google.com/dl/android/aosp/blueline-qp1a.190711.020-factory-b5633fdf.zip  这个版本的

**Comment by Avenue-le** [comment]
> 你下载的哪个包？晚上我测试一下看看



> > 你下载的哪个包？晚上我测试一下看看
> 
> https://dl.google.com/dl/android/aosp/blueline-qp1a.190711.020-factory-b5633fdf.zip 这个版本的

师傅， 你刷成功了吗？？

**Comment by dqzg12300** [comment]
我刷正常的啊。

**Comment by Avenue-le** [comment]
> 我刷正常的啊。


不是把系统img文件解压，把asop加进去，然后再打包成imgxxxx.zip, 然后刷机吗“”？

我打包成imgxxxx.zip刷不成功， 然后img压缩包解压到当前文件如下图，就刷成功了

![image](https://user-images.githubusercontent.com/34837749/193193197-09fbc015-090a-443a-a15f-0537c2ef1ada.png)

**Comment by dqzg12300** [comment]
两种方式。一种是直接改压缩包名，然后放到下载的官方包里面替换。这种适用ubuntu和mac。一般win就使用fastboot flashall -w的方式。你说的情况我没碰到。1.0.1的包我测试过是没啥问题的。或者你可以等我最新的版本出来，我会一起出一些从刷机到基础使用的视频。

**Comment by dqzg12300** [comment]
刷机视频已更新到readme，去看看应该能解决。blueline在win的刷机过程
