### ISSUE TITLE
刷rom出错

### ISSUE THREAD

**Issue by yfw123** [dqzg12300/MikRom#37]
环境：
Pixel 3
QP1A.190711.020 | android-10.0.0_r2
10.0.0 (QP1A.190711.020, Sep 2019)

错误信息:
`Writing 'vbmeta_b'                                 OKAY [  0.062s]
archive does not contain 'vbmeta_system.img'
archive does not contain 'vendor_boot.img'
archive does not contain 'super_empty.img'
archive does not contain 'boot_other.img'
archive does not contain 'odm.img'
archive does not contain 'odm_dlkm.img'
extracting product.img (312 MB) to disk... took 2.007s
archive does not contain 'product.sig'
Sending sparse 'product_b' 1/2 (262140 KB)         OKAY [  6.475s]
Writing 'product_b'                                FAILED (remote: 'Partition should be flashed in fastbootd')
fastboot: error: Command failed`

**Comment by yangmoling** [comment]
我也遇到一模一样的问题....
ubantu和 windows 一样
都是 Writing 'product_b' FAILED (remote: 'Partition should be flashed in fastbootd')

**Comment by dqzg12300** [comment]
今天晚上我发个刷机视频教程吧

**Comment by dqzg12300** [comment]
刷机视频已更新到readme，去看下把。
