### ISSUE TITLE
两个百度云的线刷包分享连接似乎都是pixel的

### ISSUE THREAD

**Issue by zixing131** [dqzg12300/MikRom#4]
两个百度云的线刷包分享连接似乎都是pixel的

**Comment by dqzg12300** [comment]
两个线刷包是aosp编译的sailfish和marlin。都是给pixel机型使用的。你是要适配什么机型的？

**Comment by zixing131** [comment]
但是两个文件是一模一样的啊，都是sailfish的

**Comment by zixing131** [comment]
顺便问一下，sailfish的线刷包要能否提供一个刷机脚本，我按照百度的方法刷入结果不开机，无限进入recovery。

**Comment by dqzg12300** [comment]
哦。看到了。尴尬，放错了。我改下。刷机方式就是去官方下个线刷包。然后解压后，修改我的压缩包名字成官方那个包名。然后运行flash-all.sh即可。

**Comment by zixing131** [comment]
大佬厉害，成功进入系统了。
