### ISSUE TITLE
com.android.settings.Settings 崩溃

### ISSUE THREAD

**Issue by ohyeah521** [dqzg12300/MikRom#41]
11-24 09:28:58.457  5335  5375 W TileUtils: Found com.android.settings.Settings$DataUsageSummaryActivity for intent Intent { act=com.android.settings.action.SETTINGS pkg=com.android.settings } missing metadata com.android.settings.category
11-24 09:28:58.468  5335  5335 D AndroidRuntime: Shutting down VM
11-24 09:28:58.468  5335  5335 E AndroidRuntime: FATAL EXCEPTION: main
11-24 09:28:58.468  5335  5335 E AndroidRuntime: Process: com.android.settings, PID: 5335
11-24 09:28:58.468  5335  5335 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.recyclerview.widget.RecyclerView$ViewHolder.isRemoved()' on a null object reference
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8528)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8523)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8511)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1641)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4115)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3832)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4385)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.View.layout(View.java:22466)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6304)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:726)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7368)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-24 09:28:58.468  5335  5335 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by dqzg12300** [comment]
打开设置就崩溃的吗？还是进入什么选项

**Comment by ohyeah521** [comment]
打开设置就崩溃

**Comment by dqzg12300** [comment]
什么机型的

**Comment by ohyeah521** [comment]
pixel4 xl

**Comment by dqzg12300** [comment]
额。我没有这个设备测试。这个可能是我改动默认权限的地方影响到的。如果你可以自己编译的话，建议尝试一下取消默认sdcard权限地方的代码试试
