### ISSUE TITLE
注入的DEX加载两次吗？

### ISSUE THREAD

**Issue by General110** [dqzg12300/MikRom#44]
https://github.com/dqzg12300/MikRom/blob/main/aosp10r2/frameworks/base/core/java/cn/mik/Fartext.java

 //注入dex
    public static void loadConfigDex(Application app){
        String processName = ActivityThread.currentProcessName();
        for(PackageItem item : mikConfigs){
            if(!item.packageName.equals(processName))
                continue;
            if(item.dexPath.length()<=0)
                continue;
            String[] dexList=item.dexPath.split("\n");
            for(String dexpath :dexList){
                loadDex(dexpath,app);  ??
                DexClassLoader dexClassLoader= loadDex(dexpath,app); ??
                Class clzz = null;

//////////////////////////////

loadDex 加载两次吗？

**Comment by dqzg12300** [comment]
这是忘记删掉拉。只需要加载一次的
