### ISSUE TITLE
希望提供一个diff文件，否则不知道代码修改了哪里，不方便理解

### ISSUE THREAD

**Issue by ohyeah521** [dqzg12300/MikRom#6]
希望提供一个diff文件，否则不知道代码修改了哪里，不方便理解

**Comment by dqzg12300** [comment]
之前未修改版备份的找不到了。我重新拉取一次后再放下diff对比的吧。先等几天吧

**Comment by dqzg12300** [comment]
diff已提交一个版本。

**Comment by ohyeah521** [comment]
> diff已提交一个版本。

貌似上传错了吧，我看还是源码啊，不是diff文件

**Comment by dqzg12300** [comment]
pixelExper_diff里面的是未修改的。应该没传错。

**Comment by ohyeah521** [comment]
> pixelExper_diff里面的是未修改的。应该没传错。

懂了，我理解的diff是 git diff  生成的东西了。
