### ISSUE TITLE
frameworks/base/cmd/mycmds

### ISSUE THREAD

**Issue by lr-zhao** [dqzg12300/MikRom#7]
存放frida so的目录应该是frameworks/base/cmds/mycmds .    作者提交的代码目录是有个小错误 frameworks/base/cmd/mycmds

**Comment by dqzg12300** [comment]
好滴。明天我修修

**Comment by lr-zhao** [comment]
> 
大佬把几个 make update-api   也写写readme 吧！ 还有个build/make/core/tasks/check_boot_jars/package_whitelist.txt  添加cn\.mik 进白名单这个文件。方便像我这种小白

**Comment by dqzg12300** [comment]
好。明天一起更新。

**Comment by lr-zhao** [comment]
> 好。明天一起更新。

完，我编译的rom 开不了机卡Android 动画，应该是system.img的问题

**Comment by dqzg12300** [comment]
也可能你没有下载对应的驱动放进去
