### ISSUE TITLE
刷的rom，frida连不上，请问下这种情况怎么解决呢

### ISSUE THREAD

**Issue by luyu344** [dqzg12300/MikRom#8]
报错如下：
A/Frida: Failed to start: Unable to create socket: Permission denied
rom为非root

**Comment by dqzg12300** [comment]
晚上我发个使用我内置的frida的视频。到时候你看下readme的更新。特地编译的非root的。避免一些检测

**Comment by luyu344** [comment]
> 晚上我发个使用我内置的frida的视频。到时候你看下readme的更新。特地编译的非root的。避免一些检测
感谢，我非root只能用script模式 非常不方便。

**Comment by dqzg12300** [comment]
已经更新说明了，你可以看下我简单演示的。https://www.bilibili.com/video/BV1RS4y137p1?spm_id_from=333.999.0.0
