### ISSUE TITLE
大佬求个 blueline 线刷包

### ISSUE THREAD

**Issue by General110** [dqzg12300/MikRom#9]
自己编译好几回了,刷了之后开不了机......没辙了,只能求大佬帮忙编译下了

**Comment by dqzg12300** [comment]
好的。明天我编译个blueline的放上去。

**Comment by General110** [comment]
> 等一段时间把。我迁移到lineageOS搞些优化了，再编译点其他版本

感谢大佬!请收下我的膝盖

**Comment by General110** [comment]
> 

成功了

**Comment by General110** [comment]
> 

成功了

**Comment by General110** [comment]
> > > 等一段时间把。我迁移到lineageOS搞些优化了，再编译点其他版本
> > 
> > 
> > 感谢大佬!请收下我的膝盖
> 
> 请问刷成功了嘛？

成功了
